/** Temporary playtest values. Damage is configurable, not a final balance decision. */
export const CONFIG = {
  arenaWidth: 72.5,
  arenaDepth: 72.5,
  movementSpeed: 15 * 1.15,
  dashDuration: 0.18,
  dashCooldown: 2.4,
  dashSpeedMultiplier: 3.3,
  botSpeed: 11.5 * 1.15,
  projectileSpeed: 64,
  shotInterval: 0.23,
  botShotInterval: 0.62,
  projectilePower: 10,
  projectileSize: 1.25,
  pickupRadius: 2.8,
  pickupReach: 0.75,
  pickupBatchSize: 8,
  pickupDelay: 0.8,
  ownPickupDelay: 5,
  victoryMinDuration: 2.4,
  victoryPickupBatchSize: 16,
  cameraZoom: 1.25,
  coreProtectionLoss: 0.6,
  characterScale: 0.5,
  maxPieces: 16000,
} as const;
